### ISSUE TITLE
feat: Interceptor + JWT 이용하여 회원가입/로그인 기능

### ISSUE THREAD

**Issue by 5win** [kakao-tech-campus-2nd-step3/Team20_BE#19]
## 회원가입/로그인
-  회원가입
-  로그인

## Todo
- [x] 회원가입 구현
- [x] 로그인 구현
- [x] 회원가입 테스트 작성
- [x] 로그인 테스트 작성
- [x] avatar, history 연동
