### ISSUE TITLE
feat: 봉사활동 기관 관련 기능 구현

### ISSUE THREAD

**Issue by 5win** [kakao-tech-campus-2nd-step3/Team20_BE#21]
## 봉사활동 기관 기능
- 기관 저장
- 기관 조회

## Todo
- [x] 컨트롤러 구현
- [x] 서비스 레이어 구현
- [x] 레포지토리 레이어 구현
- [x] 봉사활동 영속성 객체와 연관관계 매핑
- [x] 단위 테스트 작성
