### ISSUE TITLE
feat: 아바타 기능 구현

### ISSUE THREAD

**Issue by Awhn** [kakao-tech-campus-2nd-step3/Team20_BE#25]
## 유저 관련 기능(아바타) 구현
- 신규 아바타 저장
- 기존 아바타 호출
- 기존 아바타 수정
- 경험치 획득과 레벨 증가

## Todo
- [ ]  컨트롤러 구현
- [ ]  서비스 레이어 구현
- [ ]  레포지토리 레이어 구현
- [ ]  아바타 영속성 객체와 연관관계 매핑
- [ ]  단위 테스트 작성
