### ISSUE TITLE
feat: 봉사 활동 로그 관련 기능 구현

### ISSUE THREAD

**Issue by Awhn** [kakao-tech-campus-2nd-step3/Team20_BE#27]
## 봉사 활동 로그 관련 기능 구현
-  봉사 활동 로그 테이블
-  입력과 상태에 따라서 로그 기록 및 수정

## Todo
- [ ]  컨트롤러 구현
- [ ]  서비스 레이어 구현
- [ ]  레포지토리 레이어 구현
- [ ]  단위 테스트 작성
