### ISSUE TITLE
fix: 충돌 및 오류 해결 후 배포 정상화

### ISSUE THREAD

**Issue by 5win** [kakao-tech-campus-2nd-step3/Team20_BE#73]
## Todo
- [x] 데이터 수집 기능 충돌 해결
- [x] CI 실패 해결
- [x] CD 작동 정상화
