### ISSUE TITLE
feat: 가까운 거리순 정렬 조회 기능

### ISSUE THREAD

**Issue by 5win** [kakao-tech-campus-2nd-step3/Team20_BE#79]
## Todo
- [ ] 좌표 decimal 자릿수 6자리로 수정
- [ ] 거리순 정렬 조회 기능 추가
- [ ] 단위 테스트 추가
